//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daekage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daekage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daekage.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamboo.
        /// </summary>
        public static string BambooPageTitle {
            get {
                return ResourceManager.GetString("BambooPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatPageTitle {
            get {
                return ResourceManager.GetString("ChatPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the contents.
        /// </summary>
        public static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account{0}Please log in with your school account.
        /// </summary>
        public static string InvalidAccMessage {
            get {
                return ResourceManager.GetString("InvalidAccMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutBtn {
            get {
                return ResourceManager.GetString("LogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out for security{0}Please log in again.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MorePageTitle {
            get {
                return ResourceManager.GetString("MorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error!.
        /// </summary>
        public static string NetworkErrorMessage {
            get {
                return ResourceManager.GetString("NetworkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NoticePageTitle {
            get {
                return ResourceManager.GetString("NoticePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PermissionMessage {
            get {
                return ResourceManager.GetString("PermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostBtn {
            get {
                return ResourceManager.GetString("PostBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to read Karen&apos;s comments.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamboo.
        /// </summary>
        public static string ShellBambooPage {
            get {
                return ResourceManager.GetString("ShellBambooPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ShellChatPage {
            get {
                return ResourceManager.GetString("ShellChatPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string ShellMorePage {
            get {
                return ResourceManager.GetString("ShellMorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string ShellNoticePage {
            get {
                return ResourceManager.GetString("ShellNoticePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    }
}
